#!/bin/bash

function is_raspbian()
{
	grep -q -i raspbian /etc/issue > /dev/null 2>&1
}

function is_osmc()
{
	grep -q -i osmc /etc/issue > /dev/null 2>&1
}


if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi

if [ "$1" = "configure" ]; then
	if is_raspbian; then
		usermod -a -G pulse-access pi
		update-alternatives --install /usr/bin/hciconfig hciconfig /bin/hciconfig 10
	fi

	if is_osmc; then
		usermod -a -G pulse-access osmc
	fi

	systemctl daemon-reload

	systemctl enable pulseaudio.service > /dev/null 2>&1
	systemctl enable a2dp-volume.service > /dev/null 2>&1
	systemctl enable a2dp-agent.service > /dev/null 2>&1

	if ischroot; then exit 0; fi

	systemctl start pulseaudio.service > /dev/null 2>&1
	systemctl restart bluetooth.service > /dev/null 2>&1

	systemctl start a2dp-volume.service > /dev/null 2>&1
	systemctl restart a2dp-volume.service > /dev/null 2>&1

	systemctl start a2dp-agent.service > /dev/null 2>&1
	systemctl restart a2dp-agent.service > /dev/null 2>&1
	exit 0
fi
