#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

function is_raspbian()
{
	grep -q -i raspbian /etc/issue > /dev/null 2>&1
}

function is_osmc()
{
	grep -q -i osmc /etc/issue > /dev/null 2>&1
}


if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi

if [ "$1" = "remove" ]; then
	remove_divert /etc/pulse/daemon.conf.distributed /etc/pulse/daemon.conf
	remove_divert /etc/pulse/system.pa.distributed /etc/pulse/system.pa
	remove_divert /etc/bluetooth/main.conf.distributed /etc/bluetooth/main.conf
	remove_divert /etc/dbus-1/system.d/bluetooth.conf.distributed /etc/dbus-1/system.d/bluetooth.conf

	if is_raspbian; then
		gpasswd -d pi pulse-access
		update-alternatives --remove hciconfig /bin/hciconfig
	fi

	if is_osmc; then
		gpasswd -d osmc pulse-access
	fi

	systemctl restart bluetooth.service > /dev/null 2>&1
	exit 0
fi
